% Main file for performing data analysis for sequence + mental rotation
% task. Main data analysis can be performed by running the first section of
% this file. Plots can be generated by running the subsequent plotting 
% functions.
%
% Jingyan has also created a repository for analyzing this same data, which
% can be found here: https://github.com/Jingyan230/BLAMlab

clear all
rng(2);

folder = 'Data/';
subj_name = {'subj03','subj04','subj05','subj06','subj07','subj08',...
    'subj09','subj10','subj11','subj12','subj13','subj14','subj15',...
    'subj16','subj17','subj18'};

tic
data = loadData(folder,subj_name);
toc

% save data data
% load data

%% plot cursor trajectories
plot_trajectories(data)

%% plot cursor direction error data and some other kinematic data
plot_cursor_direction(data, subj_name)

%% plot fitted parameters of mixture model
plot_model_fits(data)

%% plot likelihood landscape for mixture model fits 
plot_likelihood(data)
